User Hardware Testing Tool
duckietown/duckiebot-interface pull request #80
Opened 2023-04-03 14:52 UTC by jasonhu5

This is still ongoing. It's the user testing tool from the Dashboard

2023-05-25 16:28 UTC, afdaniele requested changes

2023-05-25 16:28 UTC, afdaniele commented on packages/duckiebot_interface/include/dt_duckiebot_hardware_tests/hardware_tests.py
> +    def test_description(self) -> str:
THIs returns a `list` not a `str`

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/include/hardware_test_led/hardware_test_led.py
> +        self._led_ids = [0, 1, 2] if front_leds else [3, 4]
this list should be given by whoever is instantiating this class, do not use a binary value as a proxy for a list choice

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/include/hardware_test_led/hardware_test_led.py
> +        front_leds: bool = True,
see comment below

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/include/hardware_test_led/hardware_test_led.py
> +                samples.append((255, 0, b))
Use HSV instead

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/include/hardware_test_led/hardware_test_led.py
> +                samples.append((255, 0, b))
Example: https://github.com/duckietown/duckiematrix-examples/blob/b703ee36f68833ca843528ce1f14dd5652e01df8/vehicle/io/led/packages/example_io_led/main.py#L24-L34

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/include/hardware_test_led/hardware_test_led.py
> +                rospy.sleep(interval)
this can be parameterized and reused later when fading out

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/include/hardware_test_led/hardware_test_led.py
> +                rospy.sleep(interval)
this can be parameterized and reused above when fading in

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/include/rgb_led/rgb_led.py
> +        if self._is_performing_test and is_test_cmd or not self._is_performing_test:
simplify to `not self._is_performing_test or is_test_cmd`

2023-05-25 16:28 UTC, afdaniele commented on packages/led_driver/src/led_driver_node.py
> +        self._hardware_test_back = HardwareTestLED(self.led, front_leds=False)
use list of LEDs instead of boolean flag

2023-05-25 16:28 UTC, afdaniele commented on packages/robot_http_api/include/dt_robot_rest_api/actions/logs/__init__.py
> +        return response_not_found()
task already defined in JIRA

2023-05-25 16:28 UTC, afdaniele commented on packages/robot_http_api/include/dt_robot_rest_api/actions/logs/__init__.py
> +        #     print("Matching log:", log_f)
remove

2023-05-25 16:28 UTC, afdaniele commented on packages/robot_http_api/include/dt_robot_rest_api/actions/logs/__init__.py
> +            "search_pattern": file_pattern
rename
`number_of_logs_found` -> `count`
`dict_log_files` -> `logs`
`search_pattern` -> `pattern`

2023-05-25 16:28 UTC, afdaniele commented on packages/robot_http_api/include/dt_robot_rest_api/actions/logs/__init__.py
> +_ROBOT_HOSTNAME = socket.gethostname()
use the function `get_device_hostname()` instead.
Link: https://github.com/duckietown/dt-commons/blob/be4056555c269b152e13490165abcc2ae5e82bfc/packages/dt_device_utils/device.py#L42

2023-05-25 16:28 UTC, afdaniele commented on packages/robot_http_api/include/hardware_test_robot_host/hardware_test_robot_host.py
> +            success = False
Use a library instead, I like `netifaces`.
**Link:** https://0xbharath.github.io/python-network-programming/libraries/netifaces/index.html
**Example:**
```
>>> import netifaces
>>> from pprint import pprint
>>>
>>> pprint(netifaces.ifaddresses('eth3'))
{2: [{'addr': '192.168.1.100',
      'broadcast': '192.168.1.255',
      'netmask': '255.255.255.0'}],
 10: [{'addr': 'fe80::364b:50ff:feb7:ef1d%eth3',
       'netmask': 'ffff:ffff:ffff:ffff::/64'}],
 17: [{'addr': '34:4b:50:b7:ef:1d', 'broadcast': 'ff:ff:ff:ff:ff:ff'}]}
```

2023-05-25 16:28 UTC, afdaniele commented on packages/tof_driver/include/hardware_test_tof/hardware_test_tof.py
> +        self._sensor_name_human = " ".join(sensor_name.split("_"))  # e.g. "front center"
better 
`self._sensor_name_human = sensor_name.replace("_", " ")`

2023-05-25 16:28 UTC, afdaniele commented on packages/wheels_driver/include/hardware_test_wheels/hardware_test_motor.py
> +        dura_secs: int = 3,
`dura_secs` -> `duration` (seconds is already the standard unit of time, https://en.wikipedia.org/wiki/International_System_of_Units)

2023-06-05 14:44 UTC, afdaniele commented on packages/display_driver/include/hardware_test_oled_display/hardware_test_oled_display.py
> +            name=f"__oled_display_test__",
You don't need `f""`

2023-06-05 14:52 UTC, afdaniele requested changes

2023-06-05 14:52 UTC, afdaniele commented on packages/robot_http_api/include/dt_robot_rest_api/actions/logs/__init__.py
> +@logs_bp.route("/logs/list")
change it to "/ros/logs/list"

2023-06-05 14:52 UTC, afdaniele commented on packages/robot_http_api/include/dt_robot_rest_api/actions/logs/__init__.py
> +@logs_bp.route("/logs/download/<nodename>")
change it to "/ros/logs/download/<nodename>"

2023-06-05 17:18 UTC, jasonhu5 commented
As discussed before, I made the final updates and will merge this

2023-06-05 18:40 UTC, merged

2023-06-22 19:45 UTC, kghite reviewed
Updated a bunch of wording for clarity based on confusions I've seen with users over Slack.  Also prefer a consistent style of keeping everything in two sections - 1. preparation (where should the duckiebot be) and 2. expectations (what will you do and what will happen).  I've updated the outliers to follow that format, but feel free to revert if you feel strongly about your original format.

2023-06-22 19:45 UTC, kghite commented on packages/button_driver/include/hardware_test_button/hardware_test_button.py
> +                "Put your Duckiebot in its normal orientation, and make sure you can see and press the top button."
Place your Duckiebot on a flat surface and locate the power button on the top plate.

2023-06-22 19:45 UTC, kghite commented on packages/button_driver/include/hardware_test_button/hardware_test_button.py
> +            ]
You should see the LED in the power button blink for about {self.led_blink_secs} seconds.  When it stops blinking, press and release the button to complete the test.  Try performing this test several times to verify that pressing the power button terminates the test promptly.

2023-06-22 19:45 UTC, kghite commented on packages/camera_driver/include/hardware_test_camera/hardware_test_camera.py
> +            ["Place the Duckiebot within your reach, as you will need to move it during the test."]
Place the Duckiebot on a flat surface within your reach, and make sure that the lens cap has been removed from the camera.

2023-06-22 19:45 UTC, kghite commented on packages/camera_driver/include/hardware_test_camera/hardware_test_camera.py
> +        return self.html_util_ul(["A live camera stream should be shown below."])
You  should see a live camera stream from your Duckiebot displayed below.  Move your Duckiebot in a few directions and confirm that the camera stream is updating with the camera motion.

2023-06-22 19:45 UTC, kghite commented on packages/camera_driver/include/hardware_test_camera/hardware_test_camera.py
> +        instructions = self.html_util_ul(
Note @jasonhu5 - I think the instructions should stay in consistent places as a few of these change format.  I personally prefer that the "preparation" contains setup instructions and the "expectation" contains all other test instructions, so will stick with that in the following comments.

2023-06-22 19:45 UTC, kghite commented on packages/camera_driver/include/hardware_test_camera/hardware_test_camera.py
> +                "Move you Duckiebot for a few seconds, and check the stream corresponds to that.",
Remove extra instructions section to match other tests

2023-06-22 19:45 UTC, kghite commented on packages/display_driver/include/hardware_test_oled_display/hardware_test_oled_display.py
> +                "Put your Duckiebot in its normal orientation.",
Place your Duckiebot on a flat surface with the top OLED screen visible.

2023-06-22 19:45 UTC, kghite commented on packages/imu_driver/include/hardware_test_imu/hardware_test_imu.py
> +            [
Remove this to match the format of other tests - working it into the expectations section

2023-06-22 19:45 UTC, kghite commented on packages/imu_driver/include/hardware_test_imu/hardware_test_imu.py
> +                "Put your Duckiebot in its normal orientation, on a surface (e.g. desk).",
Place your Duckiebot on a flat surface within reach.

2023-06-22 19:45 UTC, kghite commented on packages/imu_driver/include/hardware_test_imu/hardware_test_imu.py
> +                "Once the test starts, a modal would pop up with a game.",
Once the test starts, a modal will pop up with a game.  You will see a flat plane reflecting your Duckiebot's orientation - your objective is to move the ball while keeping it on the plane.  

To play, control the plane by picking up and tilting your Duckiebot.  The test is successful if the plane moves naturally with the rotation of your Duckiebot.

2023-06-22 19:45 UTC, kghite commented on packages/led_driver/include/hardware_test_led/hardware_test_led.py
> +            ]
Place your Duckiebot on a flat surface in a position that allows you to see the {self._info_str} LEDs.

2023-06-22 19:45 UTC, kghite commented on packages/robot_http_api/include/hardware_test_robot_host/hardware_test_robot_host.py
> +            ]
Make sure the USB Wifi dongle is plugged in to your Duckiebot and is blinking.

2023-06-22 19:45 UTC, kghite commented on packages/robot_http_api/include/hardware_test_robot_host/hardware_test_robot_host.py
> +        return self.html_util_ul(["Place your Duckiebot near the charging cable."])
Place your Duckiebot on a flat surface with the charging cable plugged in.

2023-06-22 19:45 UTC, kghite commented on packages/robot_http_api/include/hardware_test_robot_host/hardware_test_robot_host.py
> +            ]
"The battery firmware version should be at least <code>2.0.2</code>.",
"The PCB version should be at least <code>16</code>.",
Run the test first with the charging cable plugged in.  Then unplug the charging cable, wait 5 seconds and rerun the test.  If the versions and charging state are correct for both tests, you can then mark the test as Success.

2023-06-22 19:45 UTC, kghite commented on packages/tof_driver/include/hardware_test_tof/hardware_test_tof.py
> +
Remove to match format of other tests. Merged into expectations.

2023-06-22 19:45 UTC, kghite commented on packages/tof_driver/include/hardware_test_tof/hardware_test_tof.py
> +            ]
Place your Duckiebot on a flat surface with at least one meter of empty space in front of the Time-of-Flight sensor on the front bumper.

2023-06-22 19:45 UTC, kghite commented on packages/wheel_encoder/include/hardware_test_wheel_encoder/hardware_test_wheel_encoder.py
> +                "Once your decide the test has passed/failed, you may mark the decision, and close this modal.",
Remove

2023-06-22 19:45 UTC, kghite commented on packages/wheels_driver/include/hardware_test_wheels/hardware_test_motor.py
> +    def test_description_preparation(self) -> str:
Place your Duckiebot upside down on a flat surface with its wheels in the air.  When you run the test, the wheels will start to spin.